// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media'
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification'

export interface Post {
	id: number;
	attributes: {
		createdAt: Date,
		updatedAt: Date,
		publishedAt?: Date,
		content: string,
		title: string,
		description: string,
		cover: { data: Media },
		locale: string,
		localizations?: { data: Post[] },
	};
}
export interface Post_Plain {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	content: string;
	title: string;
	description: string;
	cover: Media;
	locale: string;
	localizations?: Post[];
}

export interface Post_NoRelations {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	content: string;
	title: string;
	description: string;
	cover: number;
	locale: string;
	localizations?: Post[];
}

export interface Post_AdminPanelLifeCycle {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	content: string;
	title: string;
	description: string;
	cover: AdminPanelRelationPropertyModification<Media>;
	locale: string;
	localizations?: Post[];
}
