// Interface automatically generated by schemas-to-ts

export interface CarFeature {
	id: number;
	attributes: {
		createdAt: Date,
		updatedAt: Date,
		publishedAt?: Date,
		label?: string,
		icon?: any,
	};
}
export interface CarFeature_Plain {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	label?: string;
	icon?: any;
}

export interface CarFeature_NoRelations {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	label?: string;
	icon?: any;
}

export interface CarFeature_AdminPanelLifeCycle {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	label?: string;
	icon?: any;
}
