/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import fieldFormula from "strapi-plugin-field-formula/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import menus from "strapi-plugin-menus/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import reactIcons from "strapi-plugin-react-icons/strapi-admin";
import restCache from "strapi-plugin-rest-cache/strapi-admin";
import revalidateButton from "strapi-plugin-revalidate-button/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.ts";

renderAdmin(document.getElementById("strapi"), {
  customisations,
  plugins: {
    "color-picker": colorPicker,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "field-formula": fieldFormula,
    "import-export-entries": importExportEntries,
    menus: menus,
    "multi-select": multiSelect,
    "react-icons": reactIcons,
    "rest-cache": restCache,
    "revalidate-button": revalidateButton,
  },
});
